### ISSUE TITLE
Syn_filt

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#28]
filter.c

**Comment by jpj79** [comment]
I've got a multi source error showing up in synthesis.

```
ERROR:Xst:528 - Multi-source in Unit <syn_filt_pipe> on signal <unusedOverflow>; this signal is connected to multiple drivers.
```

Going by your naming conventions I modified the code to make two unused overflow signals so there would be no conflict in synthesis.

**Comment by jpj79** [comment]
Nick if you get the chance take a look at syn_filt.v and figure something out for the signal tempXReset. You never give it any values but use it as a parameter in an if/else if block.

**Comment by nickrobinson** [comment]
Clock cycles per call: 1640
Total: 1640 \* 7 = 11480 clock cycles

**Comment by nickrobinson** [comment]
I have updated the tempX problem Parker. Let me know if you run into any more problems.

**Comment by jpj79** [comment]
The behavioral simulation is running fine but in post-route we have Timing violations galore. As far as I can tell the test bench is the source of error. I will work on it and see if I can manage a solution for the meantime.

**Comment by jpj79** [comment]
All 80 outputs generated correctly in post-route. Simulated at a clock frequency of 50 MHz.

**Comment by jpj79** [comment]
When your synthesis filtering module is executing its functions in behavioral and in post-route it signals an extremely short done pulse. This occurs at the 43,190 ns mark in behavioral and it occurs when we transition from state 13 (STATE_COUNT_LOOP3_1) to state 15 (STATE_UPDATE_1).
This is due to memIn suffering a very tiny delay when its value changes from 64806 to 1. Because of this the done signal triggers very temporarily. The output generated is correct but this could be a problematic occurence in the future. If you know of any quick fixes such as removing all of your done signals to a done state, etc.. let me know otherwise I will work with you to solve this.

**Comment by jpj79** [comment]
Behavioral Timing Samples:
START: 8,310 ns
DONE: 43,630 ns
TOTAL: 1766 Clock cycles

START: 53,470 ns
DONE: 88,370 ns
TOTAL: 1745 Clock Cycles
