### ISSUE TITLE
G_pitch

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#38]
pitch.c

**Comment by jpj79** [comment]
@wolftrax84 I can't synthesize G_pitch due to more errors like the ones previously. Here is the error: <br /><br />
ERROR:HDLCompilers:28 - "G_pitch.v" line 286 'G_PITCH_SCALED_Y1' has not been declared
ERROR:HDLCompilers:28 - "G_pitch.v" line 365 'G_PITCH_SCALED_Y1' has not been declared
ERROR:HDLCompilers:28 - "G_pitch.v" line 494 'G_PITCH_SCALED_Y1' has not been declared

**Comment by jpj79** [comment]
G_Pitch ran in Post-Route and Testing Simulation at 50 MHz correctly. Here is some sampled times to determine the number of clock cycles used: <br />
    START:  223,150 ns
    DONE:   230,450 ns
    TOTAL:  365 clock cycles
<br />
    START:  613,590 ns
    DONE:   620,990 ns
    TOTAL: 370 clock cycles

**Comment by jpj79** [comment]
Behavioral timing samples
START: 15,530 ns
DONE:  22,610 ns
TOTAL:  354 Clock cycles

START: 38,310 ns
DONE:  45,390 ns
TOTAL: 354 Clock Cycles
